### ISSUE TITLE
High DPI Scaling Support

### ISSUE THREAD

**Issue by ArchLeaders** [MrMystery-Official/MapEditor#1]
On a high DPI monitor, the UI is very small and hard to use.

![image](https://github.com/MrMystery-Official/MapEditor/assets/80713508/e3601a6f-5eae-4f6e-9848-fb7886528f56)

I tried implementing this myself, but I have no knowledge of ImGui and the best I could do was hardcoding 200% scaling for my setup.

![image](https://github.com/MrMystery-Official/MapEditor/assets/80713508/24a73587-6bf4-4c5f-b9bc-c99af7cdaa13)

The dialogs are also hardcoded and the window size doesn't scale, so they are still hard to use because it's too big now.

![image](https://github.com/MrMystery-Official/MapEditor/assets/80713508/5f0f546a-47c3-4061-b3cf-6a3294f0eacb)

This is a very minor issue obviously, and I can certainly live with it. But I thought I'd mention it in case it's a relatively simple fix.

Thanks for your work, this looks great so far!

**Comment by MrMystery-Official** [comment]
Thanks for pointing that out! Fixing this bug is tough since I don't have a monitor where I can see this issue happening. Plus, this is my first time using ImGui, so I don't have much experience making a good-looking and functional user interface. Maybe I'll get around to fixing it later (or someone else might), but right now, there are other features that are higher up on the priority list. 

If you want to change the size of the PopUps, you can do it in the Frontend.cpp file. Look for the ImGuiPopUp fields, where the second and third arguments determine the size in pixels. You can adjust those values there. Alternatively, you can head into ImGuiPopUp.cpp and multiply the values there to resize them all at once.

**Comment by ArchLeaders** [comment]
Should this be left open since it's not fixed?

**Comment by MrMystery-Official** [comment]
Generally, I would leave issues open that require attention. However, in this specific case, I don't plan to fix it anytime soon. While I acknowledge the bug exists, I'm not prioritizing it at this time. I'll keep it in mind for later, but for now, I'm not actively working on resolving it.

**Comment by ArchLeaders** [comment]
That's what labels are for. You can label an issue `wontfix` and/or `helpwanted` so that other contributors still see it, but it's written off your ToDo list.

Given the scale of this project, it will be highly beneficial to have contributors, but if people don't know of these issues, likely, they won't even get fixed.

It's your project though, just thought I'd mention that as it's what most people are expecting.

**Comment by MrMystery-Official** [comment]
You are right, I should do it like this. Could you just tell me how you scaled the UI up?

**Comment by ArchLeaders** [comment]
There are two parts to the full implementation, the first part is finding the scale value of the monitor.

This can be done with `ImGui::GetWindowDpiScale();`, the catch is that this must run after the first frame is rendered which I couldn't do without breaking the render loop.

My closest attempt completely broke rendering:

![image](https://github.com/MrMystery-Official/MapEditor/assets/80713508/67ff273e-19d3-4ec8-9a56-452979135bbd)

```cpp
// [Start] First frame to register scale (breaks rendering)

ImGui_ImplGlfw_InitForOpenGL(Window, true);
ImGui_ImplOpenGL3_Init("#version 130");

glfwPollEvents();
ImGui_ImplOpenGL3_NewFrame();
ImGui_ImplGlfw_NewFrame();

glClearColor(ClearColor.x * ClearColor.w, ClearColor.y * ClearColor.w, ClearColor.z * ClearColor.w, ClearColor.w);
glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);

int width, height;
glfwGetFramebufferSize(Window, &width, &height);

ImGui::NewFrame();
ImGui::EndFrame();

// [End] First frame to register scale

float scale = ImGui::GetWindowDpiScale();
```

The second part is using the scale value to update the UI. This is quite simple to do by scaling the font size and padding values.

```cpp
// Get ImGuiStyle and ImGuiIO ...

// 1.5 is hardcoded to my setup (150%)
float scale = 1.5; // ImGui::GetWindowDpiScale();
io.Fonts->Clear();
io.Fonts->AddFontFromFileTTF("D:/Assets/Fonts/Fira-Sans/FiraSans-Regular.ttf", floor(12 * scale));
io.Fonts->Build();

style.ScaleAllSizes(scale);
```

I would have made this a pull request, except that I could not figure out how to find the source DPI scale without breaking everything.

**Comment by MrMystery-Official** [comment]
Alright, I have rewritten parts of the UI, it now uses a dock space which makes it much more dynamic. I will try my best to fix the scaling issue, but I cannot promise anything.

**Comment by MrMystery-Official** [comment]
It should be fixed now, I would be very grateful if you could test it.

**Comment by ArchLeaders** [comment]
The font has many artifacts and scales almost too much, but it's usable.

All of the documentation I've seen says to scale the font pixel size, but I can't figure out how yet.
I'm still looking though, I'll make a PR if I can find the issue. This works well for now though, thanks.

**Comment by ArchLeaders** [comment]
Update in #3
